import React from 'react';
import Head from 'next/head';
import Timer from '../components/Timer';
import Navbar from '../components/Navbar';

function cycleTwo() {
  return (
    <div className='relative z-0'>

<Head>
  <title>Nola Project</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head>

<Navbar />

<div className='absolute z-10 inset-0  flex justify-center w-screen'>
    
    <Timer />

</div>



    </div>
  )
}

export default cycleTwo