import Head from 'next/head'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Product from '../components/Product'
import ProductFour from '../public/sliderImages/ProductFour.jpg'
import  Timer  from '../components/Timer'


export default function Home() {
  return (
    <div className='relative z-0'>

      <Head>
        <title>blend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className='pt-12'>
      <Hero/>
      </div>


      <div className='mt-20 w-screen bottom-0 left-0 z-auto'>
      <Footer />
      </div>





     

      {/* <div className='grid md:grid-cols-4 max-w-[1240px] mx-auto items-center gap-2 h-screen'>
      <Product image={ProductFour} />
      <Product image={ProductFour} />
      <Product image={ProductFour} />
      <Product image={ProductFour} />
      <Product image={ProductFour} />
      
      </div> */}





    



      
    </div>
  )
}
