import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Product from '../components/Product';
import ProductFour from '../public/sliderImages/Pic7.jpg'


function productDisplay() {
  return (
    <div className='relative z-0'>

<Head>
  <title>blend</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head>

<Navbar />

<div className='absolute z-10 inset-0 w-screen h-screen flex justify-center text-black text-sm'>
    <Image alt='picture' src={ProductFour}   width='600' className='cursor-pointer'/>
</div>

<div className='absolute z-10 inset-0 w-screen h-screen flex justify-center text-black text-sm mt-[780px]'>
    <Image alt='picture' src={ProductFour}  width='600' className='cursor-pointer'/>
</div>

<div className='absolute z-10 inset-0 w-screen h-screen flex justify-center text-black text-sm mt-[1580px]'>
    <Image alt='picture' src={ProductFour}  width='600' className='cursor-pointer'/>
</div>

    </div>
  )
}

export default productDisplay