import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Link from 'next/link';
import Product from '../components/Product';
import ProductOne from '../public/product/lsg1.png';
import ProductOneSide from '../public/product/sidelsg2.png';
import ProductOneBack from '../public/product/backlsg3.png';
import Footer from '../components/Footer';
import MyListbox from '../components/MyListbox';
import {MdOutlineKeyboardArrowDown} from 'react-icons/md'


function productDisplay() {
  return (
    <div className='relative z-0'>

<Head>
  <title>blend</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head>

 <div className='md:absolute md:z-30'>
 <Navbar />
 </div>


<div className='md:absolute z-20 inset-0 flex flex-col h-screen w-screen items-center'>

<div id='picture1' className=''>
    <Image alt='picture' src={ProductOne} height='600' width='500' className='cursor-pointer'/>

</div>

<div id='picture2' >
    <Image alt='picture' src={ProductOneSide}  height='600' width='500' className='cursor-pointer'/>
</div>

<div id='picture3'>
    <Image alt='picture' src={ProductOneBack}  height='600' width='500' className='cursor-pointer'/>
</div>

</div>


<div className='md:fixed md:flex md:flex-col md:z-30 md:right-[80px] md:px-8 md:top-1 md:max-w-sm p-6'>
        <h6 className='font-bold text-lg'>LE 5 À 7 HOBO BAG IN CROCODILE-EMBOSSED LEATHER</h6>

        <p className='font-bold text-lg mt-8'>$ 2,650</p>

        <p className='lab mt-16'>SAINT LAURENT MONOGRAM HOBO BAG FEATURING AN INTERLACED METAL YSL INITIALS HOOK CLOSURE AND AN ADJUSTABLE SHOULDER STRAP.</p>

        <p className='font-bold text-md mt-8'>BLEND CYCLE</p>

        <p className='mt-4'><MyListbox /></p>

        <button className='bg-black text-white px-10 md:p-0 mt-5'>BUY</button>
        
</div>



<div className='hidden md:fixed lg:flex md:flex-col md:z-30 md:left-[370px] md:px-8 md:top-[400px] cursor-pointer'>   
        <div className='w-5 h-20'>
           <a href='#picture1'> <Image src={ProductOne} layout='fill'  /> </a>
        </div>        
</div>

<div className='hidden md:fixed lg:flex md:flex-col md:z-30 md:left-[370px] md:px-8 md:top-[490px] cursor-pointer'>   
        <div className='w-5 h-20'>
        <a href='#picture2'> <Image src={ProductOneSide} layout='fill'  /> </a>
        </div>        
</div>

<div className='hidden md:fixed lg:flex md:flex-col md:z-30 md:left-[370px] md:px-8 md:top-[580px] cursor-pointer'>   
        <div className='w-5 h-20'>
        <a href='#picture3'> <Image src={ProductOneBack} layout='fill'  /> </a>
        </div>        
</div>







<div className='absolute z-20 inset-0 mt-[1850px]'>
      <Footer />
      </div>

    </div>
  )
}

export default productDisplay